### ISSUE TITLE
SocketException in .NET Core App

### ISSUE THREAD

**Issue by Redth** [jlynch630/Harmony.NET#1]
Looks like any .net core app I run this in, I end up with:

```
Unhandled Exception: System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_DontFragment(Boolean value)
   at Harmony.DiscoveryService.BroadcastTo(String ipAddress)
   at Harmony.DiscoveryService.Broadcast()
   at Harmony.DiscoveryService.BroadcastContinually(CancellationToken token)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
```

It works fine on a standard .NET console app.

**Comment by jlynch630** [comment]
It looks like your computer is having trouble setting the DontFragment property on a UDP socket. Commit 73e9de9b7614add27a80c4c7285e37cff1646095 should fix this. 

See if installing the latest prerelease resolves your issue: `Install-Package Harmony.NET -Version 0.1.1-beta`.

**Comment by Redth** [comment]
Looks like maybe that commit didn't actually make it into `0.1.1-beta`.  I just pulled the nupkg and inspected the dll and I still see the `DontFragment` being set:

![image](https://user-images.githubusercontent.com/271950/43585382-f7fcffb2-9632-11e8-9a0a-b251fc4e7d68.png)

That being said, I pulled down the source at that commit and that change _does_ fix running in a .net core app.

If you could have a look at the release that would be great!  Appreciate the quick feedback :)

**Comment by jlynch630** [comment]
Alright, well I made sure to actually add the changes in `0.1.1` (decompiled to make sure!), and included the XML documentation comments in the latest version, `0.1.2`, if you're interested.

**Comment by Redth** [comment]
Working great now, thanks!
